# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np

2) Создать нулевой вектор размера 10

In [ ]:
zero_vector = np.zeros (10)
zero_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
sevens_vector = np.full (7,7)
sevens_vector

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
even_numbers = np.arange (10,101,2)
even_numbers

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
random_array = np.random.randint (1,100,size=10)
reversed_array = random_array [::-1]
random_array, reversed_array

(array([62, 71, 32, 87, 82, 50, 27, 22, 89, 15]),
 array([15, 89, 22, 27, 50, 82, 87, 32, 71, 62]))

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
matrix = np.arange (9).reshape (3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
import numpy as np
matrix = np.eye (4,4,k=1)
matrix

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
matrix = np.full ((4,4), 7)
np.fill_diagonal (matrix, np.arange(1,5))
matrix

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
matrix = np.tile (np.arange(5), (5,1))
matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
import numpy as np
matrix = np.random.rand(10, 10)
row_means = matrix.mean(axis=1, keepdims=True)
adjusted_matrix = matrix - row_means
matrix, adjusted_matrix

(array([[0.27948824, 0.44392473, 0.18827953, 0.87600401, 0.74641275,
         0.85962297, 0.82532385, 0.386645  , 0.5410606 , 0.88751158],
        [0.11523411, 0.07105089, 0.61573755, 0.65966407, 0.27546094,
         0.11236759, 0.14802576, 0.12337074, 0.99217381, 0.77679616],
        [0.14432018, 0.13131522, 0.92228624, 0.08743843, 0.75215469,
         0.23010585, 0.89109656, 0.93634776, 0.25628615, 0.18664906],
        [0.78569789, 0.61662229, 0.50562418, 0.09998938, 0.42778172,
         0.72725617, 0.57248879, 0.96083688, 0.35666012, 0.7624073 ],
        [0.75515561, 0.80787368, 0.88672676, 0.36714681, 0.99347373,
         0.27106694, 0.37445648, 0.84548906, 0.93215804, 0.8514877 ],
        [0.99403032, 0.49663716, 0.75926683, 0.49026739, 0.01443605,
         0.94639326, 0.297419  , 0.27872263, 0.51900018, 0.48327404],
        [0.95490498, 0.08143124, 0.63211537, 0.82312645, 0.66071688,
         0.03098073, 0.38042248, 0.4587206 , 0.56497558, 0.17410965],
        [0.96241151, 0.6755

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
matrix = np.random.rand(10, 10)
column_medians = np.median(matrix, axis=0, keepdims=True)
adjusted_matrix = matrix - column_medians
matrix, adjusted_matrix

(array([[0.047582  , 0.73731916, 0.85795563, 0.58244474, 0.8346771 ,
         0.96857349, 0.54243539, 0.96744607, 0.19377966, 0.96453613],
        [0.24194566, 0.88245814, 0.59568497, 0.0772162 , 0.61213212,
         0.31338529, 0.57449994, 0.07175101, 0.89688574, 0.96172793],
        [0.45110549, 0.1599428 , 0.61428491, 0.12630316, 0.4797257 ,
         0.33228465, 0.9476013 , 0.11768626, 0.48338327, 0.46228377],
        [0.22591932, 0.39473367, 0.03333922, 0.36716608, 0.73563732,
         0.01535269, 0.99987484, 0.04508067, 0.59353186, 0.99919317],
        [0.21213889, 0.21646716, 0.41252128, 0.1432481 , 0.58188037,
         0.00631849, 0.45482842, 0.19020066, 0.68706618, 0.46621732],
        [0.30226251, 0.05926914, 0.01702384, 0.73953165, 0.25909604,
         0.69022835, 0.57331414, 0.92909316, 0.18451502, 0.34559429],
        [0.2306268 , 0.92708716, 0.29983558, 0.01924687, 0.7391521 ,
         0.50872687, 0.50426121, 0.99956077, 0.34913542, 0.82219054],
        [0.16513588, 0.3085

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
matrix = np.random.rand(5, 5)
row_max = matrix.max(axis=1, keepdims=True)
row_min = matrix.min(axis=1, keepdims=True)
expanded_matrix = np.hstack((matrix, row_max, row_min))
matrix, expanded_matrix

(array([[0.52586299, 0.27394741, 0.74544043, 0.12591389, 0.92750248],
        [0.73418477, 0.83938924, 0.05999666, 0.83196232, 0.00114512],
        [0.30219376, 0.63369402, 0.21536507, 0.33877519, 0.32603743],
        [0.13776417, 0.46405393, 0.29589405, 0.82104781, 0.24876227],
        [0.58286567, 0.26823544, 0.00105386, 0.89740049, 0.27936961]]),
 array([[0.52586299, 0.27394741, 0.74544043, 0.12591389, 0.92750248,
         0.92750248, 0.12591389],
        [0.73418477, 0.83938924, 0.05999666, 0.83196232, 0.00114512,
         0.83938924, 0.00114512],
        [0.30219376, 0.63369402, 0.21536507, 0.33877519, 0.32603743,
         0.63369402, 0.21536507],
        [0.13776417, 0.46405393, 0.29589405, 0.82104781, 0.24876227,
         0.82104781, 0.13776417],
        [0.58286567, 0.26823544, 0.00105386, 0.89740049, 0.27936961,
         0.89740049, 0.00105386]]))

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
import numpy as np

vector = np.arange(1, 52)

odd_numbers = vector[vector % 2 != 0]
even_numbers = vector[vector % 2 == 0]


odd_matrix = odd_numbers[:25].reshape(5, 5)


even_matrix = even_numbers[:25].reshape(5, 5)


product_matrix = np.dot(odd_matrix, even_matrix)


det = np.linalg.det(product_matrix)

if det != 0:
    inverse_matrix = np.linalg.inv(product_matrix)
else:
    inverse_matrix = "Обратной матрицы не существует, так как определитель равен нулю."

odd_matrix, even_matrix, product_matrix, det, inverse_matrix

(array([[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19],
        [21, 23, 25, 27, 29],
        [31, 33, 35, 37, 39],
        [41, 43, 45, 47, 49]]),
 array([[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30],
        [32, 34, 36, 38, 40],
        [42, 44, 46, 48, 50]]),
 array([[ 750,  800,  850,  900,  950],
        [1850, 2000, 2150, 2300, 2450],
        [2950, 3200, 3450, 3700, 3950],
        [4050, 4400, 4750, 5100, 5450],
        [5150, 5600, 6050, 6500, 6950]]),
 0.0,
 'Обратной матрицы не существует, так как определитель равен нулю.')

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
matrix = [[(i + j) % 2 for j in range(8)] for i in range(8)]
for row in matrix:
    print(row)

[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
